SWIG = 'swig'

BULLET_TOP =  `ruby -e "require 'bullet_config'; print BulletConfig.get_top_dir"`
BULLET_INC = `ruby -e "require 'bullet_config'; print BulletConfig.get_inc_flags"`

OGRE_TOP = `ruby -e "require 'ogre_config'; print OgreConfig.get_top_dir"`
OGRE_INC = `ruby -e "require 'ogre_config'; print OgreConfig.get_inc_flags"`

SWIGFLAGS = "-ruby -c++ #{BULLET_INC} #{OGRE_INC} -I../src/ -I#{BULLET_TOP}/bindings/bullet/interface -I#{OGRE_TOP}/bindings/ogre/interface -autorename"


TARGET = 'teienlib_wrap.cpp'

puts SWIGFLAGS


task :default => "#{TARGET}"

file "#{TARGET}" => "teienlib.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end


task :clean do
  sh "rm -f #{TARGET}"
end

