require 'ruby-bullet'
require 'ruby-ogre'

SWIG = 'swig'
SWIGFLAGS = "-ruby -c++ #{Ruby::Bullet::get_inc_flags} #{Ruby::Ogre::get_inc_flags} -I../src/ -I#{Ruby::Bullet::get_top_path}/bindings/bullet/interface -I#{Ruby::Ogre::get_top_path}/bindings/ogre/interface -autorename"


TARGET = 'teienlib_wrap.cpp'

puts SWIGFLAGS


task :default => "#{TARGET}"

file "#{TARGET}" => "teienlib.i" do |t|
  sh "#{SWIG} #{SWIGFLAGS} -o  #{t.name} #{t.prerequisites[0]}"
end


task :clean do
  sh "rm -f #{TARGET}"
end

