#!/bin/sh

FILE_PATH=`dirname "$0"`
OGRE_LIB=`ruby -e "require 'ruby-ogre'; print Ruby::Ogre::get_deps_lib_path"`
OIS_LIB=`ruby -e "require 'ruby-ois'; print Ruby::Ois::get_deps_lib_path"`
PRO_LIB=`ruby -e "require 'ruby-procedural'; print Ruby::Procedural::get_deps_lib_path"`

LD_LIBRARY_PATH=$OGRE_LIB:$OIS_LIB:$PRO_LIB:$LD_LIBRARY_PATH ruby $FILE_PATH/hello.rb

#LD_LIBRARY_PATH=$OGRE_LIB:$OIS_LIB:$PRO_LIB:$LD_LIBRARY_PATH gdb ruby 
